### ISSUE TITLE
Create RPM package to setup SELinux

### ISSUE THREAD

**Issue by alexandrevicenzi** [kubic-project/microos-roadmap#3]
Create RPM package to setup SELinux doing the same steps as transactional-update setup-selinux.

One can look at the transactional-update sources for how setup-selinux does..and just make an RPM that does the same, then we put it on the MicroOS images

**Comment by laenion** [comment]
See https://github.com/openSUSE/transactional-update/pull/39 for reference.

If setting SELinux up from within a package works out (which would be great) I will change transactional-update to just install this package instead.

**Comment by alexandrevicenzi** [comment]
Thanks, I'll take a look into it.

**Comment by alexandrevicenzi** [comment]
I have created an initial package, [available here](https://build.opensuse.org/package/show/home:avicenzi/selinux-targeted-setup). Once installed it enables selinux, switching the setting to enforce and changing grub.

I'll send it for review soon.

**Comment by alexandrevicenzi** [comment]
The package was submitted to `devel:kubic`, [available here](https://build.opensuse.org/package/show/devel:kubic/selinux-targeted-setup).

@laenion feel free to give it a test, I think it should be easy to change `transactional-update` to use this RPM instead.

**Comment by TommyTran732** [comment]
Hi,

I have tried it on MicroOS GNOME with SELinux support. Just like with transactional-update setup-selinux, installing selinux-targeted-setup results in issues with relabeling. You can see these errors/warnings after a reboot, right before GNOME starts up.

**Comment by alexandrevicenzi** [comment]
@tommytran732 what errors are you getting? we tested on our side and it worked. Tested on MicroOS (no gui) and Tumbleweed.

You can grab the error log from dmesg or journalctl probably.

**Comment by alexandrevicenzi** [comment]
@akedroutek do you want to test this? shall we close it?

The package was created, if there's an issue with relabeling we should track it in another ticket.

**Comment by akedroutek** [comment]
this was tested ok if I remember correctly

**Comment by alexandrevicenzi** [comment]
I'm going to close this as the issue is not related to the original ticket neither seems to be reproducible.

@tommytran732 if you have more details, please, file a new ticket.
